spring:
  ai:
    mcp:
      server:
        name: demo-mcp-server
        version: 1.0.0
        type: ASYNC
        sse-message-endpoint: /mcp/messages
server:
  port: 8081
logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.ai.mcp: TRACE
    reactor.netty: DEBUG